# Generated by Django 5.0.7 on 2024-07-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='adress',
            new_name='address',
        ),
    ]
